AWSTemplateFormatVersion: '2010-09-09'
Description: "Identity created"
Parameters:
  EnvType:
    Description: Select Environment Type. Default is dev
    Type: String
    Default: dev
    AllowedValues:
      - dev
Mappings:
  dev:
    RoleName:
      Role01: tenable-dev-readonlyaccess
    PolicyArns:
      PolicyArn01: arn:aws:iam::aws:policy/ReadOnlyAccess
Resources:
  IamRole1:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - !FindInMap [ Ref: EnvType, PolicyArns, PolicyArn01 ]
      RoleName: !FindInMap [ Ref: EnvType, RoleName, Role01 ]
  IamInstanceProfile1:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
        - !Ref IamRole1
Outputs:
  OutputIamRole1:
    Value: !Ref IamRole1
    Export:
      Name: !Sub "${AWS::StackName}-IamRole1"
  OutputInstanceProfile1:
    Value: !Ref IamInstanceProfile1
    Export:
      Name: !Sub "${AWS::StackName}-IamInstanceProfile1"



